Facturacion.WebMVC/Controllers/DetalleFacturaController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Facturacion.UAPI;
using Microsoft.AspNetCore.JsonPatch.Internal;
using ProyectoFacturacion;

namespace Facturacion.WebMVC.Controllers
{
    public class DetalleFacturaController : Controller
    {
       
        private string Url = "https://facturasapi202307161115.azurewebsites.net/api/FactDetalleFacturas";
        private string Url1 = "https://facturasapi202307161115.azurewebsites.net/api/productos";

        public  ProyectoFacturacion.productos[] Productos()
        {
            var api = new System.Net.WebClient();
            api.Headers.Add("Content-Type", "application/json");
            api.Headers.Add("Authorization", "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1hdGVpdG8iLCJpYXQiOjE2ODk5NzAwOTAsImV4cCI6MTY5MDA1NjQ5MH0.M-ufLXy44Bk7_M8UKD-5pVm1fZJ-TTH9Ffi517vqBHQ");
            var json = api.DownloadString(Url1);
            return Newtonsoft.Json.JsonConvert.DeserializeObject<ProyectoFacturacion.productos[]>(json);
        }

        public  ProyectoFacturacion.productos ProductoElegido()
        {
            var api = new System.Net.WebClient();
            api.Headers.Add("Content-Type", "application/json");
            api.Headers.Add("Authorization", "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1hdGVpdG8iLCJpYXQiOjE2ODk5NzAwOTAsImV4cCI6MTY5MDA1NjQ5MH0.M-ufLXy44Bk7_M8UKD-5pVm1fZJ-TTH9Ffi517vqBHQ");
            var json = api.DownloadString(Url1);
            return Newtonsoft.Json.JsonConvert.DeserializeObject<ProyectoFacturacion.productos>(json);
        }
        private Crud<FactDetalleFactura> crud { get; set; }
        public DetalleFacturaController()
        {
            crud = new Crud<FactDetalleFactura>();
        }


        // GET: DetalleFacturaController
        public ActionResult Index()
        {
            //lista de tipos de detalle factura
            var datos = crud.Select(Url);

            return View(datos);
        }

        // GET: DetalleFacturaController/Details/5
        public ActionResult Details(int id)
        {
            var datos = crud.Select_ById(Url, id.ToString());
            return View(datos);
        }

        // GET: DetalleFacturaController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: DetalleFacturaController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(FactDetalleFactura datos)
        {
            try
            {
                crud.Insert(Url, datos);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View(datos);
            }
        }

        // GET: DetalleFacturaController/Edit/5
        public ActionResult Edit(int id)
        {
            var datos = crud.Select_ById(Url, id.ToString());
            return View(datos);
        }

        // POST: DetalleFacturaController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, FactDetalleFactura datos)
        {
            try
            {
                crud.Update(Url, id.ToString(), datos);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View(datos);
            }
        }

        // GET: DetalleFacturaController/Delete/5
        public ActionResult Delete(int id)
        {
            var datos = crud.Select_ById(Url, id.ToString());
            return View(datos);
        }

        // POST: DetalleFacturaController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, FactDetalleFactura datos)
        {
            try
            {
                crud.Delete(Url, id.ToString());
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View(datos);
            }
        }
    }
}

Facturacion.WebMVC/Controllers/FactFacturaCabeceraController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Facturacion.UAPI;
using Microsoft.AspNetCore.JsonPatch.Internal;
using ProyectoFacturacion;

namespace Facturacion.WebMVC.Controllers
{
    public class FactFacturaCabeceraController : Controller
    {
        
        private string Url = "https://facturasapi202307161115.azurewebsites.net/api/FactFacturaCabeceras";

        private Crud<FactFacturaCabecera> crud { get; set; }
        public FactFacturaCabeceraController()
        {
            crud = new Crud<FactFacturaCabecera>();
        }



        // GET: FactFacturaCabeceraController
        public ActionResult Index()
        {
            //lista de tipos de factura cabecera   
            var datos = crud.Select(Url);
            return View(datos);

        }

        // GET: FactFacturaCabeceraController/Details/5
        public ActionResult Details(int id)
        {
            var datos = crud.Select_ById(Url, id.ToString());
            return View(datos);
        }

        // GET: FactFacturaCabeceraController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: FactFacturaCabeceraController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(FactFacturaCabecera datos)
        {
            try
            {
                crud.Insert(Url, datos);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View(datos);
            }
        }

        // GET: FactFacturaCabeceraController/Edit/5
        public ActionResult Edit(int id)
        {
            var datos = crud.Select_ById(Url, id.ToString());
            return View(datos);
        }

        // POST: FactFacturaCabeceraController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, FactFacturaCabecera datos)
        {
            try
            {
                crud.Update(Url, id.ToString(), datos);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View(datos);
            }
        }

        // GET: FactFacturaCabeceraController/Delete/5
        public ActionResult Delete(int id)
        {
            var datos = crud.Select_ById(Url, id.ToString());
            return View(datos);
        }

        // POST: FactFacturaCabeceraController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, FactFacturaCabecera datos)
        {
            try
            {
                crud.Delete(Url, id.ToString());
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View(datos);
            }
        }
    }
}

Facturacion.WebMVC/Controllers/factClienteController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Facturacion.UAPI;
using Microsoft.AspNetCore.JsonPatch.Internal;
using ProyectoFacturacion;

namespace Facturacion.WebMVC.Controllers
{
    public class factClienteController : Controller
    {


        private string Url = "https://facturasapi202307161115.azurewebsites.net/api/FactClientes";

        private Crud<FactCliente> crud { get; set; }
        public factClienteController()
        {
            crud = new Crud<FactCliente>();
        }



        // GET: factClienteController
        public ActionResult Index()
        {
            //lista de tipos de factura cabecera
            var datos = crud.Select(Url);
            return View(datos);
        }

        // GET: factClienteController/Details/5
        public ActionResult Details(string id)
        {
            var datos = crud.Select_ById(Url, id);
            return View(datos);
        }

        // GET: factClienteController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: factClienteController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(FactCliente datos)
        {
            try
            {
                crud.Insert(Url, datos);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View(datos);
            }
        }

        // GET: factClienteController/Edit/5
        public ActionResult Edit(string id)
        {
            var datos = crud.Select_ById(Url, id);
            return View(datos);
        }

        // POST: factClienteController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(string id, FactCliente datos)
        {
            try
            {
                crud.Update(Url, id, datos);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View(datos);
            }
        }

        // GET: factClienteController/Delete/5
        public ActionResult Delete(string id)
        {
            var datos = crud.Select_ById(Url, id);
            return View(datos);
        }

        // POST: factClienteController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(string id, FactCliente datos)
        {
            try
            {
                crud.Delete(Url, id);    
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View(datos);
            }
        }
    }
}

Facturacion.WebMVC/Controllers/productosController.cs
using Facturacion.UAPI;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using ProyectoFacturacion;
using SQLitePCL;
using System.Net.Http;
using System.Net.Http.Headers;
using static System.Runtime.InteropServices.JavaScript.JSType;

namespace Facturacion.WebMVC.Controllers
{
    public class productosController : Controller
    {


        private string Url = "https://inventarioproductos.onrender.com/productos";

        private string Url1 = "https://facturasapi202307161115.azurewebsites.net/api/productos";
        private HttpClient GetHttpClient()
        {
            HttpClient httpClient = new HttpClient();
            httpClient.DefaultRequestHeaders.Add("Authorization", "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1hdGVpdG8iLCJpYXQiOjE2ODk5NzAwOTAsImV4cCI6MTY5MDA1NjQ5MH0.M-ufLXy44Bk7_M8UKD-5pVm1fZJ-TTH9Ffi517vqBHQ");
            return httpClient;
        }    

        private Crud<productos> crud { get; set; }


        public productosController()
        {

            crud = new Crud<productos>();
        }

        // ...otros métodos de controlador...

        public async Task<IActionResult> Index()
        {
            var datos=crud.Select(Url1); // Obtener los productos desde la base de datos local o donde sea
           
                return View(datos);
            
        }

        [HttpPost]
        public async Task<IActionResult> TransferirDatos()
        {
           try
            {

                // Crear un cliente HTTP
                using (HttpClient httpClient = new HttpClient())
                {
                    // Agregar el token de autenticación en el encabezado de autorización
                    string token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1hdGVpdG8iLCJpYXQiOjE2ODk5NzAwOTAsImV4cCI6MTY5MDA1NjQ5MH0.M-ufLXy44Bk7_M8UKD-5pVm1fZJ-TTH9Ffi517vqBHQ";
                    httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);

                    // Obtener los datos de la API externa
                    HttpResponseMessage response = await httpClient.GetAsync(Url);
                    response.EnsureSuccessStatusCode();
                    string data = await response.Content.ReadAsStringAsync();

                    // Deserializar los datos en una lista de productos
                    List<productos> productosList = JsonConvert.DeserializeObject<List<productos>>(data);

                    // Enviar los datos a la base de datos local mediante una solicitud HTTP POST
                    HttpContent content = new StringContent(JsonConvert.SerializeObject(productosList));
                    content.Headers.ContentType.MediaType = "application/json";

                    using (var localHttpClient = new HttpClient())
                    {
                        // Realizar la solicitud HTTP POST a la API local
                        HttpResponseMessage postResponse = await localHttpClient.PostAsync(Url1, content);
                        postResponse.EnsureSuccessStatusCode();
                    }
                }

                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                // Manejar cualquier excepción que pueda ocurrir durante la transferencia de datos
                // Por ejemplo, registrar el error o mostrar un mensaje de error al usuario.
                return View("Error");
            }
       }

        // GET: productosController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: productosController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: productosController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(productos datos)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    // Obtener los datos de la API externa
                    using (HttpClient httpClient = GetHttpClient())
                    {
                        var response = httpClient.GetAsync(Url).Result;
                        response.EnsureSuccessStatusCode();
                        var dato = response.Content.ReadAsStringAsync().Result;
                        var productosList = JsonConvert.DeserializeObject<List<productos>>(dato);
                        
                        // Insertar cada producto de la API externa en la base de datos local
                       
                    }

                    return RedirectToAction(nameof(Index));
                }
                catch (Exception ex)
                {
                    // Manejar cualquier excepción que pueda ocurrir durante la transferencia de datos
                    // Por ejemplo, registrar el error o mostrar un mensaje de error al usuario.
                    return View(datos);
                }
            }

            // Si el ModelState no es válido, regresar a la vista "Create" con los datos proporcionados
            return View(datos);
        }

        // GET: productosController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: productosController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: productosController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: productosController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Facturacion.WebMVC/Views/Shared/_Layout.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Proyecto Facturacion @ViewData["Title"]</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <style>
        .navbar {
            background-color: #333;
            height: 80px; /* Ajusta la altura según tus necesidades */
        }

        .navbar-brand,
        .nav-link {
            color: #fff;
            text-transform: uppercase;
            font-weight: bold;
        }

        .nav-link {
            padding: 10px 20px;
            margin: 0 5px;
            transition: background-color 0.3s;
            background-color: #007bff;
            color: #fff;
            border-radius: 5px;
        }

            .nav-link:hover,
            .nav-link:focus {
                background-color: #0056b3;
                color: #fff;
            }

            .nav-link.active {
                background-color: #0056b3;
                color: #fff;
            }

        .container {
            margin-top: 20px;
        }

        h1 {
            text-align: center;
            margin-bottom: 30px;
            text-transform: uppercase;
            color: #333;
        }

        footer {
            background-color: #f8f8f8;
            padding: 20px;
            text-align: center;
        }

        .btn-primary {
            background-color: #007bff;
            color: #fff;
            border-color: #007bff;
            border-radius: 5px;
            padding: 10px 20px;
            transition: background-color 0.3s;
        }

            .btn-primary:hover {
                background-color: #0056b3;
                border-color: #0056b3;
            }

        /* Estilos para el dropdown */
        .dropdown-menu {
            min-width: 200px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 1);
           
            
            border : 1px solid #ccc;

            border-radius: 7px;
        }

        .dropdown-item {
            color: #3271ad;
            padding: 8px 20px;
            transition: background-color 0.3s;
        }

            .dropdown-item:hover,
            .dropdown-item:focus {
                background-color: #5d7082;
                color: #000;
            }
        .navbar-toggler-icon {
            background-image: url('https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css');
            width: 24px;
            height: 24px;
        }





    </style>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Facturacion.WebMVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-dark" href="#" id="detalleFacturaDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Detalle y Cabecera
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="detalleFacturaDropdown">
                                <li>
                                    <a class="dropdown-item" asp-area="" asp-controller="DetalleFactura" asp-action="Index">Lista de Detalles</a>
                                </li>
                                <li>
                                    <a class="dropdown-item" asp-area="" asp-controller="FactFacturaCabecera" asp-action="Index">Lista de Cabeceras</a>
                                </li>
                            </ul>
                        </li>
                        
                        
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="factCliente" asp-action="Index">Clientes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="tipopago" asp-action="Index">Tipos pagos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="productos" asp-action="Index">Productos</a>
                        </li>










                       
                    </ul>
                </div>
            </div>
        </nav>
    </header>





    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Facturacion.WebMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>